docs and setup: updating Makefile to work
SovereignCloudStack/rookify pull request #72
Opened 2024-08-22 10:59 UTC by boekhorstb1

- adapting README
- adapting Makefile: outsourcing code to `scripts/` so it runs faster and better

2024-08-25 12:44 UTC, NotTheEvilOne requested changes
Please create a separate PR for the `Makefile` changes.

2024-08-25 12:44 UTC, NotTheEvilOne commented on README.md
> +**NOTE**: for testing purposes the [OSISM Testbed](https://github.com/osism/testbed) is used. The `Makefile` and example configuratino (`config.example.osism.yaml`) have built in helper functions and
Typo

2024-08-25 12:44 UTC, NotTheEvilOne commented on README.md
> +    - for the testbed there is a helper script to download the configs from the testbed. These helperscripts need correct `.ssh/config` entries to work (take a look at [scripts/get_configs_from_testb
Please move the provided testbed scripts to a `osism` sub-directory. :)

2024-08-25 12:44 UTC, NotTheEvilOne commented on README.md
> +### Provide needed configuration files from target servers
This section should be moved one up as this is the generic variant of the scripted one described.

2024-08-25 12:44 UTC, NotTheEvilOne commented on README.md
> +### OSISM Testbed
Please move this section below the generic one.

2024-08-25 12:44 UTC, NotTheEvilOne commented on README.md
> +    - make sure the id-rsa keys are "clean" and do not contain unexpected strings like "\<\<EOF"
An alternative solution would be to call `ssh-keygen -p -N "" -f ssh.key` to convert and reformat the keyfile to the expected format.

2024-08-26 08:35 UTC, boekhorstb1 commented
> Please create a separate PR for the `Makefile` changes.

ok I added makefile updates into this pr:

https://github.com/SovereignCloudStack/rookify/pull/73

2024-09-27 11:05 UTC, NotTheEvilOne requested changes
Other than that the changes look good so far.

2024-09-27 11:05 UTC, NotTheEvilOne commented on README.md
Please replace the following line:
`Kubernetes nodes should be rolled out at least on the OSD nodes`
with:
`Kubernetes nodes should be rolled out at least on the monitor nodes`

2024-09-27 11:05 UTC, NotTheEvilOne commented on README.md
> +- ssh key of the server (for the testbed they are typically found in `./terraform/.id.rsa` folder of the testbed-repository)
"found at `./terraform/.id.rsa` in the `testbed` directory"

2024-09-30 08:37 UTC, b1-lender approved these changes

2024-10-07 09:36 UTC, boekhorstb1 commented on README.md
thanks! changed that

2024-10-22 14:21 UTC, NotTheEvilOne approved these changes
LGTM

2024-10-23 07:33 UTC, merged