Prs/update makefile
SovereignCloudStack/rookify pull request #73
Opened 2024-08-26 08:35 UTC by boekhorstb1

updates to Makefile in relation to update to README.md in this PR here https://github.com/SovereignCloudStack/rookify/pull/72

2024-08-26 11:41 UTC, boekhorstb1 commented
note: currently branch is set up to merge into prs/enhance-ceph-pools

2024-09-09 09:05 UTC, boekhorstb1 commented on osism/get_configs_from_testbed.sh
change filename: get_configs_from_osism_testbed.sh

2024-09-26 07:00 UTC, NotTheEvilOne requested changes

2024-09-26 07:00 UTC, NotTheEvilOne commented on scripts/osism/get_osism_configs_from_testbed.sh
Please remove "osism" from the file name as this duplicates the directory name and is referenced (without "osism") from `Makefile`.

2024-09-26 07:00 UTC, NotTheEvilOne commented on Makefile
> +	if [ ! -f ./.venv/bin/rookify ]; then \
Please use `Makefile` target dependencies to execute dependent rules.

```
.PHONY: run-local-rookify
run-local-rookify: build-local-rookify
```

2024-09-26 07:51 UTC, boekhorstb1 commented
updated branch from main and reorganized consequently :)

2024-09-27 11:08 UTC, NotTheEvilOne commented on scripts/osism/get_osism_configs_from_testbed.sh
I would rather like the second "osism" (in file name) to be removed.

2024-10-08 07:32 UTC, boekhorstb1 commented on scripts/osism/get_osism_configs_from_testbed.sh
allright

2024-10-22 14:25 UTC, NotTheEvilOne reviewed
LGTM so far, please consider reverting your change in `README.md` to prevent merge conflicts with #72

2024-10-22 14:25 UTC, NotTheEvilOne commented on README.md
Adaptions to `README.md` are underway in #72. This file should not be changed here please :)

2024-10-23 08:06 UTC, NotTheEvilOne approved these changes

2024-10-23 08:07 UTC, merged